/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminFeedback {
  'period' : string,
  'createdAt' : bigint,
  'feedbackText' : string,
  'employeeId' : Principal,
  'overallRating' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface EmployeeProfile {
  'nip' : string,
  'kabupaten' : string,
  'nama' : string,
  'kecamatan' : string,
  'jabatan' : string,
  'lokasiKerja' : string,
}
export interface Indicator {
  'no' : bigint,
  'sumberDataEvaluasi' : string,
  'buktiDukung' : string,
  'capaianJumlah' : number,
  'capaianPersentase' : number,
  'uraian' : string,
  'targetJumlah' : number,
  'targetSatuan' : string,
}
export interface PerformanceEntry {
  'sasaranKinerja' : string,
  'period' : string,
  'indicatorList' : Array<Indicator>,
  'employeeId' : Principal,
}
export interface PerformanceSummary {
  'period' : string,
  'averageAchievement' : number,
  'employeeId' : Principal,
  'overallRating' : bigint,
  'totalObjectives' : bigint,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateFeedback' : ActorMethod<
    [Principal, string, string, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateEmployeeProfile' : ActorMethod<[EmployeeProfile], undefined>,
  'createOrUpdatePerformanceEntry' : ActorMethod<
    [string, PerformanceEntry],
    undefined
  >,
  'getAllEmployeeProfiles' : ActorMethod<[], Array<EmployeeProfile>>,
  'getAllEmployeesPerformanceSummary' : ActorMethod<
    [string],
    Array<PerformanceSummary>
  >,
  'getAllFeedback' : ActorMethod<[], Array<AdminFeedback>>,
  'getAllPerformanceEntries' : ActorMethod<[], Array<PerformanceEntry>>,
  'getCallerEmployeeProfile' : ActorMethod<[], EmployeeProfile>,
  'getCallerPerformanceEntries' : ActorMethod<[], Array<PerformanceEntry>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeedback' : ActorMethod<[Principal, string], [] | [AdminFeedback]>,
  'getFeedbackForEmployee' : ActorMethod<[Principal], Array<AdminFeedback>>,
  'getPerformanceEntriesForEmployee' : ActorMethod<
    [Principal],
    Array<PerformanceEntry>
  >,
  'getPerformanceEntry' : ActorMethod<
    [Principal, string],
    [] | [PerformanceEntry]
  >,
  'getPerformanceSummary' : ActorMethod<
    [Principal, string],
    [] | [PerformanceSummary]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'queryStatus' : ActorMethod<
    [],
    { 'accessLevel' : UserRole, 'approvalStatus' : ApprovalStatus }
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];