/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmployeeProfile = IDL.Record({
  'nip' : IDL.Text,
  'kabupaten' : IDL.Text,
  'nama' : IDL.Text,
  'kecamatan' : IDL.Text,
  'jabatan' : IDL.Text,
  'lokasiKerja' : IDL.Text,
});
export const Indicator = IDL.Record({
  'no' : IDL.Nat,
  'sumberDataEvaluasi' : IDL.Text,
  'buktiDukung' : IDL.Text,
  'capaianJumlah' : IDL.Float64,
  'capaianPersentase' : IDL.Float64,
  'uraian' : IDL.Text,
  'targetJumlah' : IDL.Float64,
  'targetSatuan' : IDL.Text,
});
export const PerformanceEntry = IDL.Record({
  'sasaranKinerja' : IDL.Text,
  'period' : IDL.Text,
  'indicatorList' : IDL.Vec(Indicator),
  'employeeId' : IDL.Principal,
});
export const PerformanceSummary = IDL.Record({
  'period' : IDL.Text,
  'averageAchievement' : IDL.Float64,
  'employeeId' : IDL.Principal,
  'overallRating' : IDL.Nat,
  'totalObjectives' : IDL.Nat,
});
export const AdminFeedback = IDL.Record({
  'period' : IDL.Text,
  'createdAt' : IDL.Int,
  'feedbackText' : IDL.Text,
  'employeeId' : IDL.Principal,
  'overallRating' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateFeedback' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateEmployeeProfile' : IDL.Func([EmployeeProfile], [], []),
  'createOrUpdatePerformanceEntry' : IDL.Func(
      [IDL.Text, PerformanceEntry],
      [],
      [],
    ),
  'getAllEmployeeProfiles' : IDL.Func(
      [],
      [IDL.Vec(EmployeeProfile)],
      ['query'],
    ),
  'getAllEmployeesPerformanceSummary' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PerformanceSummary)],
      ['query'],
    ),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(AdminFeedback)], ['query']),
  'getAllPerformanceEntries' : IDL.Func(
      [],
      [IDL.Vec(PerformanceEntry)],
      ['query'],
    ),
  'getCallerEmployeeProfile' : IDL.Func([], [EmployeeProfile], ['query']),
  'getCallerPerformanceEntries' : IDL.Func(
      [],
      [IDL.Vec(PerformanceEntry)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeedback' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(AdminFeedback)],
      ['query'],
    ),
  'getFeedbackForEmployee' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AdminFeedback)],
      ['query'],
    ),
  'getPerformanceEntriesForEmployee' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PerformanceEntry)],
      ['query'],
    ),
  'getPerformanceEntry' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(PerformanceEntry)],
      ['query'],
    ),
  'getPerformanceSummary' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(PerformanceSummary)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'queryStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'accessLevel' : UserRole,
          'approvalStatus' : ApprovalStatus,
        }),
      ],
      ['query'],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmployeeProfile = IDL.Record({
    'nip' : IDL.Text,
    'kabupaten' : IDL.Text,
    'nama' : IDL.Text,
    'kecamatan' : IDL.Text,
    'jabatan' : IDL.Text,
    'lokasiKerja' : IDL.Text,
  });
  const Indicator = IDL.Record({
    'no' : IDL.Nat,
    'sumberDataEvaluasi' : IDL.Text,
    'buktiDukung' : IDL.Text,
    'capaianJumlah' : IDL.Float64,
    'capaianPersentase' : IDL.Float64,
    'uraian' : IDL.Text,
    'targetJumlah' : IDL.Float64,
    'targetSatuan' : IDL.Text,
  });
  const PerformanceEntry = IDL.Record({
    'sasaranKinerja' : IDL.Text,
    'period' : IDL.Text,
    'indicatorList' : IDL.Vec(Indicator),
    'employeeId' : IDL.Principal,
  });
  const PerformanceSummary = IDL.Record({
    'period' : IDL.Text,
    'averageAchievement' : IDL.Float64,
    'employeeId' : IDL.Principal,
    'overallRating' : IDL.Nat,
    'totalObjectives' : IDL.Nat,
  });
  const AdminFeedback = IDL.Record({
    'period' : IDL.Text,
    'createdAt' : IDL.Int,
    'feedbackText' : IDL.Text,
    'employeeId' : IDL.Principal,
    'overallRating' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateFeedback' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateEmployeeProfile' : IDL.Func([EmployeeProfile], [], []),
    'createOrUpdatePerformanceEntry' : IDL.Func(
        [IDL.Text, PerformanceEntry],
        [],
        [],
      ),
    'getAllEmployeeProfiles' : IDL.Func(
        [],
        [IDL.Vec(EmployeeProfile)],
        ['query'],
      ),
    'getAllEmployeesPerformanceSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PerformanceSummary)],
        ['query'],
      ),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(AdminFeedback)], ['query']),
    'getAllPerformanceEntries' : IDL.Func(
        [],
        [IDL.Vec(PerformanceEntry)],
        ['query'],
      ),
    'getCallerEmployeeProfile' : IDL.Func([], [EmployeeProfile], ['query']),
    'getCallerPerformanceEntries' : IDL.Func(
        [],
        [IDL.Vec(PerformanceEntry)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeedback' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(AdminFeedback)],
        ['query'],
      ),
    'getFeedbackForEmployee' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AdminFeedback)],
        ['query'],
      ),
    'getPerformanceEntriesForEmployee' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PerformanceEntry)],
        ['query'],
      ),
    'getPerformanceEntry' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(PerformanceEntry)],
        ['query'],
      ),
    'getPerformanceSummary' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(PerformanceSummary)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'queryStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'accessLevel' : UserRole,
            'approvalStatus' : ApprovalStatus,
          }),
        ],
        ['query'],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };